### ISSUE TITLE
float() argument must be a string or a number

### ISSUE THREAD

**Issue by AllenEdgarPoe** [jjeamin/CelebA_HQ_Downloader#1]
Hi, 
I'm constantly trying to download CelebA-HQ dataset, but every repository I meet, 
I always confront with the same issue.
I've tried with your repo, because it was the most recent one, but still meets the same problem.
If it worked for your system, can you please tell me specifically about your system's environment? (ex. Numpy version etc.)  

```
Worker thread caught an exception:
Traceback (most recent call last):
  File "h5tool.py", line 97, in run
    result = func(*args)
  File "h5tool.py", line 146, in task_func
    return process_func(prepared)
  File "h5tool.py", line 556, in process_func
    img = np.pad(np.float32(img), ((pad[1], pad[3]), (pad[0], pad[2]), (0, 0)), 'reflect')
TypeError: float() argument must be a string or a number

Traceback (most recent call last):
  File "h5tool.py", line 695, in <module>
    execute_cmdline(sys.argv)
  File "h5tool.py", line 690, in execute_cmdline
    func(**vars(args))
  File "h5tool.py", line 596, in create_celeba_hq
    for orig_fn, aimg64, aimg128, aimg256, aimg512, aimg1024 in pool.process_items_concurrently(fields['idx'], process_func=process_func, max_items_in_flight=num_tasks):
  File "h5tool.py", line 161, in process_items_concurrently
    for res in retire_result(): yield res
  File "h5tool.py", line 149, in retire_result
    processed, (prepared, idx) = self.get_result(task_func)
  File "h5tool.py", line 126, in get_result
    raise result.type, result.value
TypeError: float() argument must be a string or a number
```

**Comment by jjxxmiin** [comment]
Did you make the folder structure of this repository the same?

And 

```
celebA/
  A/
    img_celeba/
    Anno/

  B/
    deltas00000.zip
    ...
    ...

CelebA_HQ_Downloader/
  h5tool.py
  ...
